'\" t
.\"     Title: idioms
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.10
.\"      Date: 2020-02-27
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "IDIOMS" "1" "2020-02-27" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
idioms \- useful functions that work within a script runtime
.SH "SYNOPSIS"
.sp
\f(CR. \fBidioms\fP\fP
.sp
\f(CReval $(\fBidioms\fP)\fP
.SH "FUNCTIONS"
.SS "\fBdie\fP"
.sp
die \- die, printing a message to standard error if given
.SS "Synopsis"
.sp
\fBdie\fP [\-e \fIERRNUM\fP] [\fIFORMAT\fP]
.SS "Options"
.sp
\fB\-e \fIERRNUM\fP\fP
.RS 4
Exit with \fIERRNUM\fP as status.
.RE
.SS "\fBerror\fP"
.sp
error \- print an error (using \fBprintf\fP(1))
.SS "Synopsis"
.sp
\fBerror\fP [\fIOPTION\fP] \fIFORMAT\fP
.SS "Options"
.sp
\fB\-d\fP
.RS 4
Die after printing the error.
.RE
.SS "\fBnote\fP"
.sp
note \- print a note (using \fBprintf\fP(1))
.SS "Synopsis"
.sp
note \fIFORMAT\fP
.SS "\fBrun\fP"
.sp
run \- print command to standard error, run it, \f(CRdie\fP if it doesn\(cqt exit successfully
.SS "Synopsis"
.sp
run [\fIOPTION\fP] \fICOMMAND\fP
.SS "Options"
.sp
\fB\-k\fP
.RS 4
Keep going if the command fails, don\(cqt \f(CRdie\fP.
.RE
.sp
\fB\-n\fP
.RS 4
Don\(cqt actually run the command, just print it.
.RE
.SS "\fBstderr\fP"
.sp
stderr \- \fBprintf\fP(1), redirected to standard error
.SS "Synopsis"
.sp
\fBstderr\fP \fIFORMAT\fP
.SS "\fBwarning\fP"
.sp
warning \- print a warning to standard error
.SS "Synopsis"
.sp
\fBwarning\fP \fIFORMAT\fP
.SH "SEE ALSO"
.sp
\fBidioms(7)\fP
.SH "BUGS"
.sp
There\(cqs an IRC channel for this and other utilities at \c
.URL "irc://irc.freenode.net/#mutiny" "" "."
Please don\(cqt hesitate to message if you have questions.
.SH "LICENSE"
.sp
\fBidioms\fP is in the public domain.
.sp
To the extent possible under law, Kylie McClain has waived all copyright and related or neighboring
rights to this work.
.sp
.URL "http://creativecommons.org/publicdomain/zero/1.0/" "" ""