= idioms(1)
:source-highlighter: rouge

== Name

idioms - useful functions that work within a script runtime

== Synopsis

`. *idioms*`

`eval $(*idioms*)`

== Functions

=== *die*

die - die, printing a message to standard error if given

==== Synopsis

*die* [-e _ERRNUM_] [_FORMAT_]

==== Options

*-e _ERRNUM_*::
    Exit with _ERRNUM_ as status.

=== *error*

error - print an error (using *printf*(1))

==== Synopsis

*error* [_OPTION_] _FORMAT_

==== Options

*-d*::
    Die after printing the error.

=== *note*

note - print a note (using *printf*(1))

==== Synopsis

note _FORMAT_

=== *run*

run - print command to standard error, run it, `die` if it doesn't exit successfully

==== Synopsis

run [_OPTION_] _COMMAND_

==== Options

*-k*::
    Keep going if the command fails, don't `die`.

*-n*::
    Don't actually run the command, just print it.

=== *stderr*

stderr - *printf*(1), redirected to standard error

==== Synopsis

*stderr* _FORMAT_

=== *warning*

warning - print a warning to standard error

==== Synopsis

*warning* _FORMAT_

== See also

*idioms(7)*

include::man/footer.adoc.template[]


