'\" t
.\"     Title: idioms-note
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.10
.\"      Date: 2020-06-17
.\"    Manual: Mutineer's Guide - idioms
.\"    Source: Mutiny
.\"  Language: English
.\"
.TH "IDIOMS\-NOTE" "3" "2020-06-17" "Mutiny" "Mutineer\(aqs Guide \- idioms"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
idioms\-note \- print a note message to standard output
.SH "SYNOPSIS"
.sp
\f(CR. \fBidioms\fP\fP
.sp
\fBnote\fP \fIMESSAGE\fP...
.SH "DESCRIPTION"
.sp
\fBnote\fP prints each \fIMESSAGE\fP to standard output, formatted like so:
.sp
.if n .RS 4
.nf
*note*: _MESSAGE_
.fi
.if n .RE
.sp
If colors are enabled (see idioms(3)), then "note" will be blue and emboldened.
.SH "SEE ALSO"
.sp
idioms(3)
.SH "BUGS"
.sp
There\(cqs an IRC channel for this and other utilities at \c
.URL "irc://irc.freenode.net/#mutiny" "" "."
Please don\(cqt hesitate to message if you have questions.
.SH "LICENSE"
.sp
\fBidioms\fP is in the public domain.
.sp
To the extent possible under law, Kylie McClain has waived all copyright and related or neighboring
rights to this work.
.sp
.URL "http://creativecommons.org/publicdomain/zero/1.0/" "" ""