= idioms(7)

== Name

idioms - overview of idiomatic utilities for scripting

== Description

*idioms* is a set of useful utilities and functions designed to make scripting more idiomatic.
It's akin to `moreutils`, but the main goal is to standardize common tasks, improve code smell, and
also make automating things like safely failing when running commands easier.

*idioms* consists of these parts:

backslash(1)::  combine lines that end with a backslash
idioms(1)::     setup usage of idioms(3) functions in a script
idioms(3)::     useful functions that work within a script runtime
integer(1)::    check if all given arguments are positve integers
lastarg(1)::    print the last argument given
match(1)::      succeed if all strings match a given pattern

== Dependencies

.Build
* make(1)

.Runtime
* A POSIX-compliant shell. (ex. bash(1), dash(1), mksh(1), busybox `ash`, etc.)
    ** An implementation of the POSIX-defined `printf` command. This might be provided by the shell
       but it can also just be a regular command without issue.
* If you wish to use the color functionality, you need a tput(1) command, likely provided by
  https://invisible-island.net/ncurses/[ncurses] or
  https://github.com/sabotage-linux/netbsd-curses[NetBSD's curses].
* For match(1): A POSIX-compliant `grep`.

.Development
* https://github.com/shellspec/shellspec[`shellspec`], if you wish to run tests.
* https://github.com/koalaman/shellcheck[shellcheck(1)], if you wish to lint files.
* https://asciidoctor.org[asciidoctor(1)], if you wish to regenerate manual pages (HTML, or manpage
  format).

include::footer.adoc[]
