= match(1)
:source-highlighter: rouge

== Name

match - return 0 if all strings match the pattern given, return 1 if strings do not.

== Synopsis

*match* [_OPTIONS_] _PATTERN_ _STRING_ ...

== Description

Exit 0 if (all) strings match the pattern given. Exit 1 if any strings do not.

== Options

*-E*::
    Use extended regular expressions. This corresponds to grep(1)'s -E option.

*-F*::
    Use a fixed, literal string. This corresponds to grep(1)'s -F option.

*-a*::
    Exit 0 if _any_ string matches, not all.

== Exit status

*0*::
    All strings matched. If *-a* was given, there was at least one match.

*1*::
    There was not a match.

== Examples

[source,shell]
----
if match "[0-9]{4}-[0-9]{2}-[0-9]{2}" "1998-05-28";then
    echo "that was a date!"
else
    echo "please give a date instead"
fi
----

== See also

grep(1), expr(1)

== Authors

include::AUTHORS[]

There's an IRC channel for this and other idiom utilities at #mutiny@irc.freenode.net. Please don't
hesitate to message if you have questions.

== License

*match* is in the public domain.

To the extent possible under law, Kylie McClain has waived all copyright and related or neighboring
rights to this work.

http://creativecommons.org/publicdomain/zero/1.0/

